### ISSUE TITLE
some question about dataset

### ISSUE THREAD

**Issue by liwk1616** [q1xiangchen/VMPs#3]
I'm really interested in your research, and sincerely want to rebuild it. But in the github project, I can't find the mpii_split.py file you mentioned, can you provide it or teach me how to get the correct training, testing and validation set?

**Comment by q1xiangchen** [comment]
Thank you for your interest! The code has been updated. Please have a look.

**Comment by liwk1616** [comment]
Thank you very much for your prompt response. I have resolved the issue now. I am not very proficient in English, so please forgive me if there are any issues with my expression.




李
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "q1xiangchen/VMPs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月30日(星期三) 上午10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [q1xiangchen/VMPs] some question about dataset (Issue #3)





 
Thank you for your interest! The code has been updated. Please have a look.
